### ISSUE TITLE
Elastic Trailing Buy and Sell

### ISSUE THREAD

**Issue by Othon3** [taniman/profit-trailer-enhancements#133]
profit-trailer-enhancements

Implement a way that trailing would be more dynamic, with elastic propertiers.

I explain: For the trailing buy for example, as the price moves downwards, traling becomes shorter and shorter by a degree measured in % of the pattern to estimate how far the price could rally.
If we set a buy_value of -1  and a trailing of 0.30  . Once the price reaches the -1 the bot starts trailing for 0.30 dip. As it passes the -1.3 mark, trailing would decrease buy a x% , and so forth.  The ideia is to get the lowest price possible to buy.  It the price goes back up, it wouldn´t have to go all the way up the 0.3 trailing, but only a % of it, measured from the lowest point in relation to the first trigger.

The same logic would apply to trailing profit. As the price moves higher than our sell_value and the bot starts traling, the trailing value would become smaller and smaller as the price moves higher above the triggered price. In the same result, this would try to get the higher price possible to sell it.

**Comment by RunPlz** [comment]
Yes!

**Comment by Utone** [comment]
Genius solution to this static problem sir! *bows*

I would like to add, to your suggestion because your idea gets me thrilled and reminds me of this love hate relationship with trailing and some of the crude solutions I had thought of after encountering some situations where its not in your advantage to use it.

When the next 'real milestone' is here enabling you guys to buy real dips instead of DCA'ing your way into them: 
Not giving it away here: The lowest dip doesn't go any lower...

A mayor one:
After x% profit in dumps after pumps: auto disable trailing profit entirely 
It currently prevents selling when the price drops..I was lucky to have spotted the odd high percentage thinking it was a dust trade, but which turned out to be a DCA pumped to 88%...with over 4.5K in profit swiftly dropping...costing me at least a grand in the retarded process..

I never understood 'panic sell' thought it 'ridiculous as i usually am very content, thrilled perhaps but panic never had entered into the lovely adrenaline and dopamine infused mix of emotions when selling and buying.. 

Until THAT moment....

After removing trailing profit from the pair config (Yes 'luck or thinking ahead' would have it DCA was already disabled so it already was there or I had to fetch a few more lines (as if I'm not mistaken you cant do anything pair specific in DCA so a panic sell would sell all DCA pairs which is only logical)

The 'PANIC ' in sell increased each time it popped back up after a partial fill and to further fuel the panic with an increasing mix of emotions rarely felt: frustration, contempt, disbelief and disillusion and some I can only describe as abstractions exclusively for that moment alone...
When PT apparently needed to recalculate the average price after each partial filled sell (not a buy mind you, just to point it out to some that might overlook why this is completely unnecessary)
To partially sell again at 50%, 34%,...13...and after franticly typing PAIR_panic_sell_enabled = true the final portion of the position sold for a measly 2.3% 

I had finally experienced the mysterious 'panic' while selling.
I often find some of the worst experiences to become the best and most hilarious memories later and already cherish this priceless experience. Smiling while writing on github about fucups (sic) is a wonderful thing.

BUTT preventing 'panic' in general is in my and everyones best interest and I would be a prick not to mention it in this context.  (PT still handles some of my bags not yet suitable to undergo special treatment and some of my manual buys)

Some users may not even be aware they (/are) potentially missing(/missed) out on some huge profits on some of the bags they are holding...
just have a 

#_panic_sell_enabled = true 
line ready to copy paste...

Call me a ranter or whatever..Just be thankful I (still) take the effort to maybe help some of your paying customers (I already tried to tell you a few times but your feeble little ego prevents it.. no dick swinging contest needed here..If it was you alone Elroy I would ignore it too, its easier that way..yes hihi...)

Bye now ;p

**Comment by clownfish44** [comment]
Already requested here https://github.com/taniman/profit-trailer-enhancements/issues/60

**Comment by Othon3** [comment]
Actually request #60  is quite the opposite of this one..

Ass the valuegets higher, trail_profit would decrese, and not increase, as stated on #60

**Comment by AkliOnet** [comment]
https://github.com/taniman/profit-trailer/issues/227
