### ISSUE TITLE
Stochastic / Stochastic RSI Indicators Support

### ISSUE THREAD

**Issue by Uruwashii** [taniman/profit-trailer-enhancements#16]
the ability to use as an option Stochastic / Stochastic RSI indicators

**Comment by BitStreamGains** [comment]
Adding to this so as not to open another ticket... In addition to adding these specific indicators and others like **MACD**, make it so that the strategies are layered and **require confirmation** so that **all conditions must be met for a buy**. Example... RSI must be below 20 on 15 min chart AND Stochastics must be below 20 on the 60 min chart AND EMAGAIN must be at least -0.5 on the 5 min chart. **IF all of those are true then buy.** These strategies can be implemented via TradingView Charts if the exchange does not have access to them. This should provide good protection for staying out of bags. It is important to have the multiple chart times per indicator and not all indicators on the same chart time. 
Code may look something like...

`{
   buy conditions:
      {
        TriggerType: AND, //Setting to AND means all have to be true to buy
           {
            Stochastics: 
                {
                 AtOrBelow: 20,
                 TimeFrame: 60 //minutes
                }
           }
            RSI: 
                {
                 AtOrBelow: 20,
                 TimeFrame: 15
                }
           }
            EMAGAIN
                {
                 AtOrBelow: -0.5,
                 EMA1: 12,
                 EMA2: 24
                }
           }
      }
}`

**Comment by iAmVaeVictus** [comment]
Agree. Would like to be able to vote on WHICH indicators we add next. Should be able to combine these indicators, and should include one from each category to start with: volume based, price based, volatility based, so we can get confirmation indicators from different categories so that we don't mistakenly use confirmations from the same type of indicator. 

NEW Candidates would include: 
RSI, MFI, BB % (squeeze), Ichimoku, Intraday Intensity, accumulation/distribution, Volume Weighted MACD, MACD, On Balance Volume, Volume-Price Trend, Negative/Positive Volume Indices.

**Comment by dutchy1966** [comment]
YES Pleasssse more indicators (RSI, macd etc.) AS mentioned above possibilty to add then together.

**Comment by clownfish44** [comment]
Already been requested and added to the next milestone here https://github.com/taniman/profit-trailer/issues/370

**Comment by CryptoTalks** [comment]
Defintely condition based options. 

i.e. If (x) & (y) = (z) THEN (a,b,c) 

I feel this is the only advantage software like CryptoHopper have over PT..
