### ISSUE TITLE
A MaxCost function that Indicate % of your current BALANCE

### ISSUE THREAD

**Issue by hcmikejj** [taniman/profit-trailer-enhancements#160]
Indicate % of total current BALANCE (TCB) of account we will use to buy.

For example, if you have a total value of $10000 and you have 4 of the (max) 8 pairs with bags, if those bags take like 80% of your (TCV) total current value you have $2000 left in your balance (TCB). If you buy with 3% of your TCV you buy a coin for $300, this don't make sense if you have only $2000 left. Now if you buy with ALL_max_cost_balance_based_percentage (TCB) you can trade with your full balance because now you are using TCB = 3% ($60) of the $2000 you have left!

According to reply on my previous message this function is already existing but i can't find it in the wiki for some weeks now!!

**Comment by Julianjg4186** [comment]
Very true

**Comment by clownfish44** [comment]
Requested here https://github.com/taniman/profit-trailer-enhancements/issues/186 with much better explanation.

**Comment by chostetler15** [comment]
I had a similar idea #186 but took it a step further and added a curve function to help users be more or less aggressive with the money they have left. What you are describing is my straight blue line in my graph, which I think would be great for 90% of users! 

This feature could really help people that over extend themselves and get deep into the DCA. They can keep playing with the little bit of money they have left rather than sitting on bags for days/weeks and making nothing.
