### ISSUE TITLE
DCA Trailing buy per trigger

### ISSUE THREAD

**Issue by fjdelaba** [taniman/profit-trailer-enhancements#230]
Hi, i would think it would be interesting if we can have a trailing buy per lvl, as most people do, we have a low % loss on the first triggers so a trailing of say, .2 it´s what we use, but from trigger 5 or 6 most people go to -5% or -8% for the triggers, so i would like a .6 or something like that as a trailing buy.

Another way of putting it, is that trailing buy on DCA should be a % of the trigger, not the same absolute value for every trigger.

**Comment by vlasvlasvlas** [comment]
+1

**Comment by ccp89** [comment]
+1

**Comment by onizeayanami** [comment]
+1

**Comment by JulianSas** [comment]
+1

**Comment by securitygeneration** [comment]
Was thinking about this today. When the price is really going down and you're at your -12% trigger, you probably want to trail for longer (e.g. 1-2%) rather than a usual 0.2-0.7%

We need a trigger_X_trailing_buy setting...

**Comment by storxusmc** [comment]
The only issue with this is it can get to high that the bot is unable to react to the rate change enough to actually ever buy...

I was trying to mimic something like this and setup my DCA config trailing buy to 1.0, and i watched it drop multiple % to the bottom of a selloff for the market only to react to quickly back up off the bottom before the bot read the 1.0% change.. it ended up missing a 8% drop in value over 5 minutes on a DCA buy of 2% and trailing of 1.0, instead of buying down at the bottom around the 8%, it bought at 3.2% price mark.. because the price moved to quickly off the bottom for it to place an order that would go filled...

**Comment by ilmarioranen** [comment]
I won't bother writing a separate feature request, but I'd just like to comment here that in addition to a separate trailing buy per trigger level, I would really appreciate the ability to override DCA settings per coin, instead of using one global set.

Since the few DCA-settings in my opinion have a huge influence on the output, it would be great if we could allow our most trusted coins to have much deeper DCA-levels than generic shitcoins.

**Comment by clownfish44** [comment]
Per dca level trailing has already been requested here https://github.com/taniman/profit-trailer/issues/292 and accepted to a future release
