### ISSUE TITLE
Feature Request - Manual Sell Button

### ISSUE THREAD

**Issue by jorgebouche** [taniman/profit-trailer-enhancements#241]
Would be great if a manual sell button for each active pair could be applied to the GUI in the both the pairs and DCA logs. Allows for more control over sell time, even with trailing.

**Comment by securitygeneration** [comment]
I'd really like this too. There are a number of times I felt a pair were ready to be sold (even if they didn't meet the sale criteria defined in the properties), and it would be nice to be able to trigger the sell within PT (and have PT track the profit/loss), rather than go into the exchange and do it).

**Comment by clownfish44** [comment]
Same concept linked here and added https://github.com/taniman/profit-trailer/issues/360
