### ISSUE TITLE
Please bring back Total Pending Value (TPV)

### ISSUE THREAD

**Issue by sannyd** [taniman/profit-trailer-enhancements#277]
Very much helps us to determine what our value would be and doesn't assume loss because of a bag.

**Comment by clownfish44** [comment]
This will not be brought back to ProfitTrailer. This was highly inaccurate in pt 2.0 as with multiple sell strats and per dca trigger sell strats it was simply not possible to have any reasonable estimate as well as all coins sell above the triggers.

**Comment by NOP-Commander** [comment]
Hi @clownfish44,

https://wiki.profittrailer.com/doku.php?id=web_interface_guide1
_TPV (Total Pending Value) - The cost value of your bags. It's the sum of your BAL (balance) and the money you spent in your actual trades (it's how much you could get if you sold them at their bought price)._

I seriously don't understand why summing up the costs and the balance of your market currency can be affected by strategies. Are the cost values shown in the GUI (Pairs->Bought Cost, DCA->Tot.Cost) and not shown in GUI (Pending->Tot.Cost.) not correct (anymore? since 2.x?) and therefore the sum of it wouldn't be correct either?

I mean TPV never was meant to be a profit-projection but a value which reflected the costs of your positions. Sorry for bothering but removing something which your community (or let's better say the part of the community participating here and there on GitHub) liked and like to have back is leaving us somehow unsatisfied. It's not about the rejection of this issue itself, it's the removal of a feature we found and still find useful. And for an average Joe like me, without any knowledge about the code of cause, TPV is easy to calculate and isn't affected by strategies unless we have different understanding of "costs".

Thanks in advance for an answer.
