### ISSUE TITLE
Build bot restart functionality into the URL

### ISSUE THREAD

**Issue by kingokeke** [taniman/profit-trailer-enhancements#306]
Hi devs. Great work so far. I have a suggestion. Can you build a bot restart functionality into the URL? Just like you have the URL command to stop the bot, you can also have a URL command to restart the bot. Would be very convenient. Thanks.

**Comment by NOP-Commander** [comment]
Another additional option could be, when a restart is triggered, to write a dummy file to a configurable path on the filesystem so that a cronjob running every minute could check for existence and fire the restart with os-dependent techniques. in my case (linux) it would run systemctl restart "servicename". Others might prefer pm2 or run windows with powershell magic via task scheduler. Just a thought.

**Comment by NOP-Commander** [comment]
Nice said. 😄 But you're right basically. It's just me being too nerdish. But nevertheless even with URL this would be a nice feature to have, even for a nerds like me. We can use curl and wget to handle URLs. 😄

**Comment by clownfish44** [comment]
This is not possible as a program can not restart its self without an external monitor / restart service

**Comment by kingokeke** [comment]
Maybe you could write an implementation of this and forward to the team so they can integrate it. A conditional flow to check for os and run the appropriate command which will all be triggered by the cURL and wget stuff. Just a thought. They'd probably induct you as an hononary member of the PT dev team.

**Comment by NOP-Commander** [comment]
I would love to support you guys in that case but i never coded in Java. Lately I'm limited to shell-scripting and occasionally perl. Sorry but come back again if i can help in a way i'm able to.
