### ISSUE TITLE
Allow EMACROSS to be used as a sell strategy (#884 reinstated)

### ISSUE THREAD

**Issue by aludden** [taniman/profit-trailer-enhancements#342]
#884 just got closed, saying that V2 allows it. That is not really true. Yes, you can set it, but since GAIN is mandatory, if the cross happens just below a gain (which happens quite often), PT does not sell and you're left with a bag. The whole point of selling on EMACROSS is to avoid bags (even if it results in a small loss). It should act like Stop Loss does. This seems to be a popular request, there are several with different wordings, so I'm not alone. Thanks!

**Comment by aludden** [comment]
I was told to try setting the GAIN at -100. I didn't try that before because the wiki says that GAIN has to be zero or greater. I will try that and report back. If so, the wiki should be amended. Thanks!

**Comment by RANIRAK39** [comment]
How hard would it be to just allow it to sell exactly on the cross, witrhout any gain setting at all?? Would be a much easier way to swing trade longs and shorts!! Someone needs to program this!

**Comment by DmitryBychenko** [comment]
#357

**Comment by robheath90** [comment]
aludden, setting GAIN as a negative value does work, however trailing doesn't work (the coin gets stuck true trailing for as long as it is negative. My GAIN is set at -20% and the bot sells correctly.

I've found 2 solutions to this problem but none are ideal:

1) disable trailing for selling. This allows the coin to sell at a loss, as both GAIN and EMACROSS become true. the problem of course is that EMACROSS initially often crosses on a big red candle, which will sell at a significant loss
2) (This is the method I use) Upon purchasing each coin I use HotConfig to adjust the price to a low value, giving me for example a 10% profit (and setting GAIN as true). This then allows trailing_profit to work successfully. The problem here is that it gives falsely positive sell logs, and requires significant manual input.

I've mentioned this on a few threads tonight as I came to investigate this same issue, but as GAIN works when a coin is negative, enabling trailing for any value above the (GAIN - trail) price, whether the GAIN is positive or negative, will solve this issue and essentially allow EMACROSS/MACD to be used a combined sell strategy and stoploss.

**Comment by robheath90** [comment]
@aludden, what lengths and candles are you using? I found my success is better the longer my candles are.

what I've actually done is switched from EMACROSS to MACD, using day candles. I find the signals come more quickly after a big drop, and EMACROSS really does lag badly. Go on Tradingview or similar, and compare the two methods using day candles. Even using pessimistic candles, both should be profitable. I initially started using 30-minute candles, but I saw that far too often I was buying peaks and selling dips.

**Comment by aludden** [comment]
@robheath90 , thanks, I will try that!

**Comment by DmitryBychenko** [comment]
Im looking for the same thing, and was trying to set GAIN to negative value. Technically it works, but this is not what we need. Shortly, if current Profit for example 4%, bot will never sell the coin because there is no signal to start selling (signal is GAIN). 

This is how it look like:
https://www.dropbox.com/s/8h8qcra4hcq3jmt/gain-1.png?dl=0

Profit is 3.19 and 2.60, but bot will close these trades at stoploss after price (Profit) stay at that values 1 hour - 1 day - 3 days or whatever and finally hit stoploss which is set at -1%.

There is another issue with negative GAIN - trailing starts work when Profit is negative. 
The thing is we need trailing when Profit is positive, and dont need trailing if Profit is negative.
It gets too complicated, and this all is wrong way.

Better way is to have normal positive GAIN (+ another Sell strategies if needed) AND sell by some indicator signal, for example, sell by SMACROSS at the same time.
If there is indicator signal (SMACROSS) bot should sell the coin, if no signal - bot should reach normal positive GAIN value and start profit_trailing. 

I offered a solution for this problem in topic #357.

Solution shortly:

Get one more constant, name it for example DEFAULT_A_forcesell_strategy = XXXX,

Example of strategy:

DEFAULT_A_sell_strategy = GAIN
DEFAULT_A_sell_value = 2.0

DEFAULT_B_sell_strategy = RSI
DEFAULT_B_sell_value = 65

DEFAULT_trailing_profit = 0.35
DEFAULT_stop_loss_trigger = -1

DEFAULT_A_forcesell_strategy = SMACROSS (solution)
DEFAULT_A_forcesell_value = -0.1 (solution)

How should it work:

1. If there was signal to sell (SMACROSS in this case), bot should sell the coin
2. If there was no signal to sell (SMACROSS), bot should follow normal sell strategy:

DEFAULT_A_sell_strategy = GAIN
DEFAULT_A_sell_value = 2.0

DEFAULT_B_sell_strategy = RSI
DEFAULT_B_sell_value = 65

DEFAULT_trailing_profit = 0.35
DEFAULT_stop_loss_trigger = -1

If it makes sence, support topik #357 with Like, or leave some comment.

**Comment by Masterofcoinak** [comment]
Since Gain is not mandatory anymore. Should be closed.
