### ISSUE TITLE
Price_Drop_Escape_Pair: move current balance to escape pair when market drops X%

### ISSUE THREAD

**Issue by weirders** [taniman/profit-trailer-enhancements#363]
Currently SOM triggers when your specified pair goes down. With that, the value of your base pair still keeps dropping. To counter this, it would be useful if there was logic to move the current balance into an Escape pair, USDT for example. Thus shielding your current balance from further devaluation. 

* Trigger structure would be equal to SOM, but the ability to set it different would be useful as you could go in SOM a bit earlier than actually moving base balance.
* Including auto recover settings, same as SOM.
* There might also be a use case for a Panic Sell All first then move balance to Escape_pair, but this would be an extreme move. 

Trading benefit: I believe above could have a fairly large positive effect on saving balance value when the market drops. Even dodging a few % drops on one's balance, which is in value usually much larger than a normal pair, could have significant impact.

**Comment by Ichy84** [comment]
Yes, in my opinion the best suggestion so far.
And i am for the what you called extreme move. If btc bleeds panic sell wont do any good, because you will still loose in value. If you "escape pair" the base currency, you will still loose money with the other pairs (if the whole market is down). So both steps are required.
