### ISSUE TITLE
Trailing profit separate from Sell strategies

### ISSUE THREAD

**Issue by fletch63** [taniman/profit-trailer-enhancements#457]
It would be nice to have a switch that you will allow PT to trail profit even if all sell strategies are not true.  In other words separate the trailing profit from the sell strategies

**Comment by Masterofcoinak** [comment]
Should be closed.
Use:
DEFAULT_sell_strategy_formula
DEFAULT_sell_strategy_formula =
Coin Specific - click for more infoOptional - click for more info

Valid values: Any valid set of properly formatted strategies using javascript operators; examples below.

Note:

Formatted strings follow the order of operations and uses AND ( && ), OR ( || ), NOT ( ! ).
You must use parenthesis to delimit what you want to add together, i.e.- you cannot use A && B || C because the bot will not know whether you want to use A and B together OR C .. or whether you want to use A ….and B OR C.
Example:

DEFAULT_sell_strategy_formula = (A && B) || C
Will look for either: A and B strategies to be TRUE , OR for the C strategy to be TRUE.

DEFAULT_sell_strategy_formula = A || B
Will look for either: A OR B strategies to be true.

DEFAULT_sell_strategy_formula = A || B || (C && D)
Will look for either: A strategy to be TRUE , OR for the B strategy to be TRUE, OR for the C AND D strategies to be TRUE.

**Comment by LiamAird** [comment]
For reference: http://wiki.profittrailer.com/doku.php?id=pairs.properties#default_sell_strategy_formula
