### ISSUE TITLE
PtTracker Functionality Built In / Better Graphs, Stats, And Much More Info!

### ISSUE THREAD

**Issue by junkchaser** [taniman/profit-trailer-enhancements#5]
http://pttracker.net/

This function should be a part of PT for a long time.

**Comment by LeaderOfChampions** [comment]
Agreed, there should be a portion of Profit Trailer that digs into statistics and data of your historical trades and presents graphs and running totals.

**Comment by Neilfau** [comment]
Agreed this is much needed!

**Comment by CryptoFiles** [comment]
We need this!

**Comment by clownfish44** [comment]
All sorts of stats, graphs, and statistics tracking will be linked here

**Comment by juato4** [comment]
this and #76 are the best!

**Comment by CousinEddie** [comment]
+1

**Comment by tru-fkn-blu** [comment]
+1

**Comment by Tosko4** [comment]
+1

**Comment by elementalwindx** [comment]
#146 has nothing to do with pt tracker yet it's linked here...

**Comment by norova** [comment]
+1

**Comment by sininger** [comment]
This all seems superficial and inconsequential to the bigger picture. The list of opportunity for functions should be purely that: function. Talk to me about RSI influence integration and a realistic buy volume scaling and forget about things that are of little consequence, arbitrary buy value, for example. 

Crypto is what it is because of the volatility which is largely due to the swings from almost no volume to unreasonable volume in the matter of minutes. That means a measure of buy value updated every 4-10 minutes is simply counter intuitive. 

My two suggestions are not to add but to improve:
1 - focus on making what already works better and faster
2 - BB, EMA, and BLABLA may be applicable to a regulated market. However, crypto is not that. An "outside the box" thinker may look into establishing new metrics of measurement in pattern, time, etc.

**Comment by sininger** [comment]
ML - because AI doesn't exist.

**Comment by WesNz** [comment]
+1 definately needed!

**Comment by nicnic22** [comment]
Please also include losses so we will be able to get a precise idea of how much money is gained AND lost.

**Comment by nagsve** [comment]
We need all trade information organized thinking on future IRS requirements.

**Comment by briersben** [comment]
+1
Integration with PT Tracker would be a very nice addition indeed! I guess no need to reinvent the wheel. It would be nice for people like me, who already bought PT Tracker, to be able to activate the tracking functionalities of PT Tracker, preferably integrated in the PT Monitoring (front-end) page.

Currently, I disabled PT Tracker since I am running a Ubuntu VPS and I was having some doubt about security, as the pt-tracker files reside in the PT directory and in order for PT Tracker to run you need to start a webserver on the PT directory. Not exacly sure how safe this is..

**Comment by cobuscoetsee** [comment]
Just merge/buy PT Tracker ;) meaning faster rollout happy community.  
Advantages. 
1. Team A looking after buy strategies and logic
2. Team B looking after front-end interface 

Best of both worlds.

**Comment by jshay21** [comment]
I would vote for native integration with PT Magic

**Comment by BitRacer** [comment]
totally want this, I got pttracker, and honestly, the reporting and stats are nice,  but not worth the $$, seems like it should be build in anyway.  To their credit, I'm happy they use the APIs.

**Comment by clownfish44** [comment]
Issue accepted!

**Comment by jarrettwil** [comment]
Is PT Tracker capable of being used without using ProfitTrailer? If not, it'd be awesome if it was able to.

**Comment by jarrettwil** [comment]
Can PT Tracker be used independent of ProfitTrailer? There just aren't any trade trackers I like so far...
