### ISSUE TITLE
[Feature request]Partial sells

### ISSUE THREAD

**Issue by PTMaza** [taniman/profit-trailer-enhancements#599]
It will be sweet to be able to get partial sells. to be able to sell % of positions according to some targets. 

20% gain ==> sell 10% position
40% gain ==> sell 30% position
etc. 

Cheers and thanks

**Comment by W1949M** [comment]
My feature idea is similar without the sells based on gain, which I think wouldn't really function as well with the bot.  I do like yours as well though as it does serve the purpose I'm wishing for too.  I want to accumulate long term while also selling and buying the volatile coins because I think all of us agree when Bitcoin breaks 30k it would be nice to have a stack of each other successful smaller coin to sell off and get the monies.

**Comment by PTMaza** [comment]
No because when I will reach my sell value %, 100% of my positions will be sell. You want to keep going Holding some if I understand.

**Comment by W1949M** [comment]
Ah yes you're right.  I would like to save some ultimately though I do feel our goals are similar.  Hopefully they can implement the reserve amount in the future since I think people really want to hold some coins over time as well without fearing blowing up their account if they're wrong.

**Comment by taniman** [comment]
SOX_take_profit does this
