### ISSUE TITLE
[FEATURE REQUEST]  Add "wait x candles after cross" setting to SMA/EMACross strategy

### ISSUE THREAD

**Issue by bagkido** [taniman/profit-trailer-enhancements#646]
Hi, I'm suggesting adding one more setting for SMA/EMAcross strategy. ie. wait x candles (or minutes) after cross.

This is very common yet useful setting for this strategy in stock trading, particularly if trading on a relatively mid to long term (2hr 4hr or daily candle). This is to prevent "false" cross signal caused by sudden dump-and-pump. For eg. if using 4hr candle, if price suddenly moves it could cause a cross signal and the bot execute a buy. The next hour the price recovers so the cross signal no longer true so the bot immediately execute an opposite trade (this is what i actually experienced during the past 2 days....BTC price saw sudden dump-and-pump). The "wait x candles after cross" setting is to confirm the cross is a "true" signal.

I'm running a 4 hr EMAcross strategy on a testmode and last 2 days BTC price is really volatile. So 

Hope this setting could be added into SMA/EMAcross strategy parameters.

**Comment by taniman** [comment]
But what you are asking here coud be accomplished by using only_closed_candles functionality. This way only the value updates only after the candle is fully closed.
Or you can specify only_closed_candles_period

so say ema is on 4 hours
you can do only closed candles period is 1 hour
so the value updates every 1 hour candle instead of every 4 hours
