### ISSUE TITLE
Different Sell Stategy Depending on Buy Strategy.

### ISSUE THREAD

**Issue by jeotalavera180** [taniman/profit-trailer-enhancements#747]
for example if i have two buy strategies, bb or ma. 

how can i tell the bot to have different sell strategy based on the strategy it bought?
other features like trailing too.

this is good because you want to exit differently depending different on your entry.

**Comment by taniman** [comment]
This would be achievable with the logic that was built for 2.5.0 that will allow you to look at the buy history and built your formulas based on that info. 
Only issue would be that if you are using trailing buy, once trailing starts the buy strategies are ignored and we trail only the price by default. So the strategies might turn false again.

so once the buy happen and a strategy turned false again because of trailing you can't know what strategy caused the buy to happen

So you will need to either disable trailing or use reset trailing with strategies and then you would be able to exactly know which strategies caused your buy and be able to sell based on those strategies.

That's the best we can do in 2.5.0 for now

**Comment by taniman** [comment]
What you are proposing is the same as looking at the buy history. Because if you group it, still the bot would need to know which strategy bought. And that is buy looking at the buy history.

So you are proposing to build some that you could already do yourself now using the SBH(X) logic

**Comment by ivalstar** [comment]
Is it? Isn't SBH(X) returning the value? So let's say I use VWAPPERCENTAGE as buy strat and the value is -0.3 when the buy occurs. I could then test this value to decide which sell strat to use.
Instead I'd like to something like this:
var used_buy_strat = BUYSTRAT1;
if (used_buy_strat == BUYSTRAT1) {
   use sell_strat1;
} 
So, regardless of the value.

Unless I misunderstand the use of SBH(X) of course...

**Comment by taniman** [comment]
I understand what you would like to do. But that is you trying to have a shortcut and now wanting to type it all out.

If I have Strategy with letter A and the buy_value = 20.
Meaning it buys when RSI is below 20


Now I want to check if this strategy was the one that bought. I can simply check 
SBHA < 20 ?

That causes you to type a bit more but it yields the same result.

**Comment by ivalstar** [comment]
Well, the point is, I use tv-signals, like so:
DEFAULT_A_buy_strategy = SIGNAL
DEFAULT_A_buy_strategy_label = TV1
DEFAULT_B_buy_strategy = SIGNAL
DEFAULT_B_buy_strategy_label = TV2

I have no idea what the buy_value is, so how can I check it? Is it the price where the coin was bought? No way to figure out which strat was used.

So instead of testing the value, I'd like to know if A or B (or C && D) was used and test that:
SBHS = A ?
Where SBHS would be the triggered strategy.

This would be possible if we could name the strategies and this name is stored in SBHS.

It would also make https://github.com/taniman/profit-trailer-enhancements/issues/891#issue-1027582736 possible.

**Comment by taniman** [comment]
I am 99% sure I answered a similar question to this in our Discord not too long ago.
When the signal is true it returns the current price information as BSV.
So it is a matter of checking if SBHA or B or whatever was bigger than 0.

Also this all should go in Discord, as I mentioned with a little work on your part it is possible to achieve so there is no reason for me to build extra logic as of now
