### ISSUE TITLE
GUI for creating config files

### ISSUE THREAD

**Issue by junkchaser** [taniman/profit-trailer-enhancements#9]
As most community questions are how the configs work ("you can find it in the wiki" - no you don't) let's create a GUI for setting the variables of the config files, while the results are viewed on a graph, so people can have more visible feedback of the changes they've made.

**Comment by iAmVaeVictus** [comment]
What would be useful here is the ability to more easily transition the config files to new config files if there are additions or deletions in those files. Something like a line by line comparison of the settings with a copy , add, delete feature for each setting. This would be in the browser ideally. 

EXAMPLE: 

OLD FILE...................................| NEW FILE .................................| ACTIONS (clickable)...............|
ALL_trading_enabled = true......| ALL_trading_enabled = false ...| Copy from Old Settings
ALL_trading_pairs = BTC-ETH..| ALALL_trading_pairs = ALL......| Copy from Old Settings
..................................................| BTC-XXX_DCA_enabled = true | Add to Settings
some_old_setting = true ...........|..................................................| Remove from Settings


This would eliminate a lot of support issues with people making typos in their settings, leaving out settings that are needed. It would include form validation for all the settings to catch errors like ALL_trading_enabled = TRUE.

**Comment by rsdaltx** [comment]
Hell yeah!

**Comment by lars974** [comment]
To me that's THE feature that could really make the project big and mainstream. Any serious project needs a user-friendly interface and not to set manually data into variables through file editions.

**Comment by chostetler15** [comment]
I like this idea a lot. It could use an "example" coin and plot a hypothetical chart (potentially changes on refresh). On this chart you could manually change your buy/sell strategies, indicators and DCAs and it would show you on the hypothetical chart where your settings would have bought and sold. 

This wouldn't need "backtesting" on every coin, since it is using a fake chart. But it would allow users to better understand what their settings are doing!

Check out this example I mocked up. It will show when your settings would trail, buy, and sell. You can adjust your numbers, then refresh the chart to a new example, and see if your settings work there as well. 

![buy-strategy-demo](https://user-images.githubusercontent.com/32551211/37134626-37c4f252-224e-11e8-8a51-0a0a8e724b62.png)

**Comment by clownfish44** [comment]
In the works for 2.0 or 2.1
